_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: IOURPN
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    IOU_LABELS:
      - 0
      - -1
      - 1
    IOU_THRESHOLDS:
      - 0.3
      - 0.7
  ROI_HEADS:
    NAME: Res5ROIHeadsStep8
    OUTPUT_LAYER: ClipOutputLayersStep8
    BASETRAIN: True
    POT_THRESH: 0.11
    NUM_CLASSES: 60
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
    IOU_LABELS:
      - 0
      - 1
    IOU_THRESHOLDS:
      - 0.5
DATASETS:
  TRAIN: ('coco14_trainval_base',)
  TEST: ('coco14_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (85000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 20000
  CLIP_GRADIENTS:
    CLIP_VALUE: 35.0
    ENABLED: True
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/Path/to/Output/Dir"