_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: IOURPN
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    IOU_LABELS:
      - 0
      - -1
      - 1
    IOU_THRESHOLDS:
      - 0.3
      - 0.7
    FREEZE: False
  ROI_HEADS:
    NAME: Res5ROIHeadsStep8
    OUTPUT_LAYER: ClipOutputLayersStep8
    BASETRAIN: False
    POT_THRESH: 0.5
    NUM_CLASSES: 80
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    IOU_LABELS:
      - 0
      - 1
    IOU_THRESHOLDS:
      - 0.5
DATASETS:
  TRAIN: ('coco14_trainval_all_10shot_seedx',)
  TEST: ('coco14_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (4800,)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
  CLIP_GRADIENTS:
    CLIP_VALUE: 35.0
    ENABLED: True
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
OUTPUT_DIR: "/Path/to/Output/Dir"